### ISSUE TITLE
issue reading config from docstring

### ISSUE THREAD

**Issue by rbturnbull** [smutch/snakedoc#23]
I'm having trouble with it reading this docstring:

```
    List path to alignment files into a single text file for use in PhyKIT.

    If the `infer_tree_with_protein_seqs` config variable is True, then it uses the protein alignments
    otherwise it uses the threaded CDS sequences.

    :config: infer_tree_with_protein_seqs
```

It dies at snakedoc/smk.py line 110:

```
    key = node[0][0].split(" ")[1]
```

**Comment by rbturnbull** [comment]
I've seen how the doc strings should be from the mccoy repo. I think we'd just need some error checking in the code here.

**Comment by rbturnbull** [comment]
@smutch is there a way to have config descriptions run over multiple lines?

**Comment by smutch** [comment]
If I understand correctly then this is an example: https://github.com/mccoy-devs/mccoy/blob/351f5c6ce5604c4b8a153f236262fc3d88a02787/mccoy/workflow/rules/tree.smk#L13
The RST indentation is just a bit fiddley...

The config entries are top level though. i.e. you can't currently embed a :config: directive inside a :param: directive (at least I've never tried to do that). If that is desired then let me know though and I'll try to implement it if I can.

Happy for any and all feature requests as I'm using orthoflow and McCoy as the two test cases to get everything to a v0.1 stage before release.

**Comment by smutch** [comment]
Closing as it seems that this was a formatting issue rather than a bug or feature request.
