### ISSUE TITLE
resolve relative path to smk_configfile

### ISSUE THREAD

**Issue by rbturnbull** [smutch/snakedoc#24]
At the moment smk_configfile is just a string. I think it should resolve to a Path object that is relative to the config file that it is in. Does that work for you @smutch ?

**Comment by rbturnbull** [comment]
the current code means that the file is relative to the working directory of where you run sphinx-build which isn't ideal.

**Comment by smutch** [comment]
I think that makes sense. I'll have a look this week... I typically think of config files as if they were command line arguments defined in a file instead of on the command line, which is why the paths work the way they do at the moment. I can see pros and cons for each case though and I'm not married to the current definition...

**Comment by smutch** [comment]
Although I do see that the Sphinx convention is to be relative to the config directory and then for that to be something which can be overridden on the command line with the `-c` option. Snakedoc should definitely follow that convention too...

**Comment by smutch** [comment]
@rbturnbull can you give [this branch](https://github.com/smutch/snakedoc/tree/deps/smk-bibtex-relative_paths) a go and let me know if that works as you would expect. Not that I have had to remove some assumptions about project structure and so you must now also include a `smk_linkcode_basepath` entry in the Sphinx `conf.py`. Basically all source codes links will replace `smk_linkcode_basepath` in the paths with `smk_linkcode_baseurl` to construct the URL for the source code link.

**Comment by smutch** [comment]
I will actually replace `smf_linkcode_basepath` and `smk_linkcode_baseurl` with a single `smk_linkcode_mapping` parameter before merging the PR, but if you could let me know if the existing approach even works as you would expect first then that would be grand. :)
